apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: build-image
spec:
  params:
    - name: IMAGE
      type: string
  workspaces:
    - name: source
  steps:
    - name: build
      image: quay.io/buildah/stable
      securityContext:
        privileged: true
      workingDir: /workspace/source
      script: |
        buildah bud -t $(params.IMAGE) .
        buildah push $(params.IMAGE)
