apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: nodejs-lint
spec:
  workspaces:
    - name: source
  steps:
    - name: lint
      image: node:18
      workingDir: /workspace/source
      script: |
        npm install
        npm run lint
