apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: jest-test
spec:
  workspaces:
    - name: source
  steps:
    - name: run-jest
      image: node:18
      workingDir: $(workspaces.source.path)
      script: |
        npm install
        npm test
