apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: deploy-openshift
spec:
  params:
    - name: APP_NAME
      type: string
    - name: IMAGE
      type: string
  steps:
    - name: deploy
      image: quay.io/openshift/origin-cli
      script: |
        oc set image deployment/$(params.APP_NAME) \
        $(params.APP_NAME)=$(params.IMAGE)
